"""M8 ToolRegistry — Register, list, and execute agent tools."""
from __future__ import annotations
import asyncio, logging, os
from typing import Any, Callable, Dict, List, Optional

log = logging.getLogger("m8.tools")


class Tool:
    def __init__(self, name: str, description: str, fn: Callable):
        self.name        = name
        self.description = description
        self._fn         = fn

    async def run(self, input_str: str, session_context: Optional[Dict] = None) -> str:
        try:
            if asyncio.iscoroutinefunction(self._fn):
                return await self._fn(input_str, session_context)
            loop = asyncio.get_event_loop()
            return await loop.run_in_executor(None, self._fn, input_str)
        except Exception as e:
            log.error("Tool %s error: %s", self.name, e)
            return f"Tool error: {e}"


class ToolRegistry:
    def __init__(self):
        self._tools: Dict[str, Tool] = {}

    def register(self, tool: Tool):
        self._tools[tool.name] = tool

    def register_many(self, tools: List[Tool]):
        for t in tools:
            self.register(t)

    def get(self, name: str) -> Optional[Tool]:
        return self._tools.get(name)

    def list_tools(self) -> List[Dict]:
        return [{"name": t.name, "description": t.description} for t in self._tools.values()]


def built_in_tools() -> List[Tool]:
    """Return the standard built-in tool set."""

    async def think_fn(input_str: str, ctx=None) -> str:
        """Pure reasoning step — just returns the input as a formatted thought."""
        return f"💭 Reasoning:\n{input_str}"

    async def web_search_fn(query: str, ctx=None) -> str:
        """Simulated web search — replace with real search API."""
        try:
            import httpx
            url = f"https://ddg-api.herokuapp.com/search?query={query}&limit=3"
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.get(url)
                if resp.status_code == 200:
                    data = resp.json()
                    snippets = [f"• {r['title']}: {r['snippet']}" for r in data.get("results", [])[:3]]
                    return "\n".join(snippets) if snippets else "No results."
        except Exception:
            pass
        return f"[Web search results for: {query}] — configure SEARCH_API_KEY for live results."

    async def summarize_fn(text: str, ctx=None) -> str:
        """Summarize long text."""
        if len(text) < 500:
            return text
        return f"Summary of {len(text)} chars:\n" + text[:400] + "…"

    async def write_fn(prompt: str, ctx=None) -> str:
        """Generate written content."""
        return f"[Draft content for: {prompt}]\n\nThis would be generated by the configured LLM provider."

    async def retrieve_fn(query: str, ctx=None) -> str:
        """Retrieve from knowledge base (ChromaDB)."""
        try:
            import chromadb
            client = chromadb.Client()
            collections = client.list_collections()
            if not collections:
                return "No knowledge collections found."
            col = client.get_collection(collections[0].name)
            results = col.query(query_texts=[query], n_results=3)
            docs = results.get("documents", [[]])[0]
            return "\n---\n".join(docs) if docs else "No relevant documents found."
        except Exception as e:
            return f"Knowledge retrieval unavailable: {e}"

    async def code_exec_fn(code: str, ctx=None) -> str:
        """Safely execute Python code in a sandboxed namespace."""
        namespace: Dict[str, Any] = {}
        output_lines: List[str] = []

        def safe_print(*args, **kwargs):
            output_lines.append(" ".join(str(a) for a in args))

        namespace["print"] = safe_print
        try:
            exec(compile(code, "<agent>", "exec"), namespace)  # noqa: S102
            return "\n".join(output_lines) or "(no output)"
        except Exception as e:
            return f"Execution error: {type(e).__name__}: {e}"

    return [
        Tool("think",      "Pure reasoning / chain-of-thought",            think_fn),
        Tool("web_search", "Search the web for current information",        web_search_fn),
        Tool("summarize",  "Summarize long text into key points",           summarize_fn),
        Tool("write",      "Generate written content from a prompt",        write_fn),
        Tool("retrieve",   "Retrieve relevant docs from knowledge base",    retrieve_fn),
        Tool("code_exec",  "Execute Python code and return stdout output",  code_exec_fn),
    ]
